### ISSUE TITLE
What is this ? Sorry )

### ISSUE THREAD

**Issue by linuxenko** [hemanth/life-expectancy#1]
Hey, @hemanth , i'm following you, i like many things you do , can you please explain a little bit the data means , what is `rank` and another numbers means ? Thank you.

**Comment by hemanth** [comment]
NP. Hoping that [more-info](https://github.com/hemanth/life-expectancy/blob/master/readme.md#more-info) makes sense.

**Comment by linuxenko** [comment]
Thank you !
